# Generated by Django 4.2.15 on 2024-08-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameStatus',
            field=models.CharField(choices=[('W', 'win'), ('L', 'lose')], default='', max_length=1),
        ),
    ]
