# Generated by Django 4.2.15 on 2024-08-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
