# Generated by Django 4.2.15 on 2024-08-18 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_player_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gameStatus',
        ),
        migrations.RemoveField(
            model_name='game',
            name='type',
        ),
    ]
