# Generated by Django 4.2.15 on 2024-08-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_remove_game_created_at_remove_game_gamestatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='game',
            name='gameStatus',
            field=models.CharField(choices=[('W', 'win'), ('L', 'lose')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='game',
            name='type',
            field=models.CharField(choices=[('TR', 'tournament'), ('MP', 'multiplayer')], default='', max_length=2),
        ),
    ]
