# Generated by Django 4.2.15 on 2024-08-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_game_created_at_game_gamestatus_game_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='player_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
