# Generated by Django 4.2.16 on 2024-09-26 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_game_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='name',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player_id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='points',
        ),
        migrations.AddField(
            model_name='player',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
        migrations.AddField(
            model_name='player',
            name='is_host',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='gameStatus',
            field=models.CharField(choices=[('STARTED', 'started'), ('WAITING', 'waiting')], default='', max_length=7),
        ),
    ]
