# Generated by Django 4.2.16 on 2024-09-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_remove_game_name_remove_game_player_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player_count',
            field=models.IntegerField(default=0),
        ),
    ]
