# Generated by Django 4.2.16 on 2024-09-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_remove_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='settings',
            field=models.JSONField(null=True),
        ),
    ]
