# Generated by Django 5.1.1 on 2025-02-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0002_profile_is_oauth2'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='oauth2_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
