# Generated by Django 5.1.1 on 2025-02-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0003_profile_oauth2_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pic_updated',
            field=models.BooleanField(default=False),
        ),
    ]
