# Generated by Django 5.1.1 on 2025-02-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0006_alter_profile_oauth2_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='oauth2_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
