# Generated by Django 5.1.2 on 2024-11-01 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('player_count', models.IntegerField(default=0)),
                ('gameStatus', models.CharField(choices=[('STARTED', 'started'), ('WAITING', 'waiting')], default='', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_host', models.BooleanField(default=False)),
                ('game_result', models.CharField(choices=[('W', 'W'), ('L', 'L')], default='L', max_length=1)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='multiplayer.game')),
            ],
        ),
    ]
