# Generated by Django 4.2.16 on 2024-11-02 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='settings',
        ),
    ]
