# Generated by Django 4.2.16 on 2024-09-26 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_game_player_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='type',
        ),
    ]
