# Generated by Django 5.1.4 on 2024-12-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_player_game_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='gameStatus',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player_count',
        ),
        migrations.RemoveField(
            model_name='game',
            name='settings',
        ),
        migrations.RemoveField(
            model_name='player',
            name='game_result',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_host',
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('LOST', 'won'), ('WON', 'lost')], default='', max_length=7),
        ),
        migrations.AddField(
            model_name='game',
            name='type',
            field=models.CharField(default='Remote', max_length=50),
        ),
    ]
