# Generated by Django 5.1.4 on 2024-12-14 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_remove_player_game_remove_player_status_game_player1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='created_at',
            new_name='date_time',
        ),
    ]
