# Generated by Django 5.1.4 on 2024-12-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_rename_created_at_game_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date_time',
            field=models.DateField(auto_created=True),
        ),
    ]
