# Generated by Django 5.1.4 on 2024-12-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_alter_game_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='username',
        ),
        migrations.AddField(
            model_name='player',
            name='userId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
