# Generated by Django 5.1.4 on 2024-12-22 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_remove_player_username_player_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='games',
            new_name='total_games',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='points',
            new_name='total_points',
        ),
    ]
