# Generated by Django 5.1.4 on 2024-12-25 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_rename_games_player_total_games_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiplayerGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('team1_points', models.IntegerField(default=0)),
                ('team2_points', models.IntegerField(default=0)),
                ('player1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multi_player1_games', to='game.player')),
                ('player2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multi_player2_games', to='game.player')),
                ('player3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multi_player3_games', to='game.player')),
                ('player4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multi_player4_games', to='game.player')),
                ('winner1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multi_winner1', to='game.player')),
                ('winner2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multi_winner2', to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='RemoteGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('player1_points', models.IntegerField(default=0)),
                ('player2_points', models.IntegerField(default=0)),
                ('player1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remote_player1_games', to='game.player')),
                ('player2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remote_player2_games', to='game.player')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remote_winner', to='game.player')),
            ],
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
