# Generated by Django 5.1.4 on 2024-12-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_multiplayergame_remotegame_delete_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='username',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
