# Generated by Django 5.1.4 on 2025-01-08 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_player_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='rank',
        ),
    ]
