# Generated by Django 5.1.4 on 2025-01-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_remove_player_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='total_games',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='total_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='userId',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
