# Generated by Django 5.1.4 on 2025-01-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_alter_player_level_alter_player_total_games_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='level',
            field=models.FloatField(default=0),
        ),
    ]
