# Generated by Django 5.1.4 on 2025-01-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_alter_player_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='type',
            field=models.CharField(default='remote', max_length=20),
        ),
    ]
