# Generated by Django 5.1.4 on 2025-01-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_player_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='type',
        ),
        migrations.AddField(
            model_name='remotegame',
            name='type',
            field=models.CharField(default='remote', max_length=20),
        ),
    ]
