# Generated by Django 5.1.4 on 2025-01-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_remove_player_type_remotegame_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplayergame',
            name='type',
            field=models.CharField(default='multiplayer', max_length=20),
        ),
    ]
