# Generated by Django 5.1.4 on 2024-12-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification_receiver_alter_notification_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.TextField(default='sent you a playing request', max_length=150),
        ),
        migrations.AlterField(
            model_name='notification',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
