# Generated by Django 5.1.4 on 2024-12-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification_sender_alter_notification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('seen', 'seen'), ('delivred', 'delivred')], default='delivred', max_length=50),
        ),
    ]
