# Generated by Django 5.1.4 on 2025-01-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_notification_receiver_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='userId',
            new_name='receiverId',
        ),
        migrations.AddField(
            model_name='notification',
            name='senderId',
            field=models.IntegerField(default=0),
        ),
    ]
