# Generated by Django 5.1.4 on 2025-01-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_notification_receiver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
        migrations.AddField(
            model_name='notification',
            name='seen',
            field=models.CharField(default=False),
        ),
    ]
