version: '3'

services:
    backend:
        build: ./backend
        image: backend
        container_name: backend
        ports: 
          - '8000:8000'
        volumes:
            - ./backend/srcs:/app/

# volumes:
#   backend:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: '/nfs/homes/houaslam/Desktop/gamePart'
