# Generated by Django 5.1.1 on 2024-12-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_oauth2',
            field=models.BooleanField(default=False),
        ),
    ]
